# Domain settings
scheme: "http"
domain: "tristan.dev.uctf.io"

# DNS settings
dns:
  infomaniak:
    token: "An6QaR9jfCsSkcBg-jbAYzI3zV4XZRxk-1r-ZeE4fawpb0BCHWRjpPCzGami-6LweSK6p5XkEXJUiFPF"

# PostgreSQL settings
postgres:
  localHost: "localhost"
  localPort: 5432
  host: "postgresql.external.svc.cluster.local"
  port: 5432
  admin:
    user: "postgres"
    password: "postgres-admin-password" 
    database: "postgres"
  users:
    - name: "basilic"
      password: "basilic"
      databases:
        - "basilic"

# Services settings
services:
  - name: "basilic"
    path: ../basilic
