apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fake-smtp-route
  namespace: external
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway
  hostnames:
    - "mail.{{.Domain}}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fake-smtp-nodeport
          port: 1080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgweb
  namespace: external
spec:
  parentRefs:
    - name: main-gateway
      namespace: gateway
  hostnames:
    - "pgweb.{{.Domain}}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pgweb
          port: 8081
